use sql_project;
create table clothing_data
(
Date date,	
Year int,
Month varchar (20),
Store varchar (50),
Category varchar (50),
Brand varchar (50),
Quantity_Sold	int,
Unit_Price decimal(10,6),	
Payment_Method	varchar (50),
Total_Sale decimal (10,6)
);
select * from clothing_data;
select count(*) from clothing_data;
update clothing_data
SET date = STR_TO_DATE(date, '%d/%m/%Y')
WHERE date NOT LIKE '____-__-__';

select * from clothing_data
where date is null
or year is null
or month is null
or store is null
or category is null
or brand is null
or quantity_sold is null
or unit_price is null
or payment_method is null
or total_sale is null;

-- 1. Find the total number of records in the dataset.
select count(*) from clothing_data;

-- 2  Display all unique store names.
select distinct store from clothing_data;

-- 3 List all unique product categories.
select distinct category from clothing_data;

-- 4 Show total sales for each store.
select store,sum(total_sale) as total_sales
from clothing_data
group by store;

-- 5  Find the highest total sale amount in the dataset.
select max(total_sale) as highest_sales from clothing_data;

-- 6 Find the total sales made in each month.
select * from clothing_data;
select month,sum(total_sale) as total_sales
from clothing_data
group by month;

-- 7 Calculate the total quantity sold per category.
select category,sum(quantity_sold) as total_quantity
from clothing_data
group by category;

-- 8 Find the average unit price for each brand.
select * from clothing_data;
select brand,avg(unit_price) as average_of_unit_price
from clothing_data
group by brand
order by average_of_unit_price desc;

-- 9 Show the top 5 brands with the highest total sales.
select brand,sum(total_sale) as total_sales
from clothing_data
group by brand
order by total_sales desc
limit 5;

-- 10 Identify which payment method was used most frequently.
select payment_method,count(*) as most_used
from clothing_data
group by payment_method
order by most_used desc
limit 1;

-- 11 Calculate the total revenue generated by each store and category combination.
select * from clothing_data;
select store,category,sum(total_sale) as total_revenue
from clothing_data
group by store,category
order by total_revenue desc;

-- 12 Find the month with the highest total sales.
select month,sum(total_sale) as highest_total_sales
from clothing_data
group by month
order by highest_total_sales desc
limit 1;

-- 13 List all transactions where the total sale is greater than 1000.
select * from clothing_data
where total_sale>1000;

-- 14 Identify the top 3 stores based on total sales.
select store,sum(total_sale) as best_sale
from clothing_data
group by store
order by best_sale desc
limit 3;

-- 15 Categorize sales by time period (e.g., Morning, Afternoon, Evening) using the CASE statement.
SELECT 
    Store,
    Total_Sale,
    CASE 
        WHEN EXTRACT(HOUR FROM Date) BETWEEN 6 AND 11 THEN 'Morning'
        WHEN EXTRACT(HOUR FROM Date) BETWEEN 12 AND 17 THEN 'Afternoon'
        WHEN EXTRACT(HOUR FROM Date) BETWEEN 18 AND 23 THEN 'Evening'
        ELSE 'Night'
    END AS Time_Period
FROM clothing_data;
